#!/bin/bash

#PBS -N DR2_setup
#PBS -l nodes=1:ppn=1
#PBS -l walltime=100:00:00
#Pbs -m abe

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

export IMAGEDIR=/data1/tap/data/images/P21
export PYTHONPATH=/data1/tap/ids/lotss-catalogue/utils:/data1/intema/lofarpipeline/RL-Xid/LOFAR/DR2:${.}
export RLDIR=/data1/tap/ids/RL-Xid/P21_Test/P21_${PBS_ARRAYID}

FIL=P21_${PBS_ARRAYID}
DIR=/data1/tap/ids/RL-Xid/P21_Test_${PBS_ARRAYID}

echo Changing to directory ${DIR} and running on file ${FIL}
cd ${DIR}

python ../../DR2/DR2_setup.py ${FIL}.fits /data1/tap/results/component_association_catalogues/P21/LoTSS_predicted_v0.comp.fits
