#!/bin/bash

#PBS -N DR2_setup
#PBS -l nodes=1:ppn=1
#PBS -l walltime=100:00:00
#Pbs -m abe

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

export IMAGEDIR=/data/lofar/DR2/
export PYTHONPATH=/home/mjh/lofar/catalogues:/home/mjh/git/lotss-catalogue/utils/:/soft/python/lib64/python2.7/site-packages

FIL=spring${PBS_ARRAYID}
DIR=/beegfs/lofar/jcroston/surveys/weave_production/spring/spring${PBS_ARRAYID}

echo Changing to directory ${DIR} and running on file ${FIL}

cp ${FIL}.fits radio.fits